import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState, useEffect } from "react";
import { Phone, Envelope, MapPin, LinkedinLogo, YoutubeLogo, TelegramLogo, FacebookLogo, X, PaperPlaneTilt, } from "@phosphor-icons/react";
import { BRAND, SOCIAL } from "../constants";
const TELEGRAM_AVATAR = "https://miltoengineering.com/wp-content/uploads/2023/07/photo_2023-07-30_04-43-59-e1690717691292.jpg";
function TelegramWidget() {
    const [isOpen, setIsOpen] = useState(false);
    const [currentTime, setCurrentTime] = useState("");
    useEffect(() => {
        const update = () => setCurrentTime(new Date().toLocaleTimeString("en-US", {
            hour: "2-digit",
            minute: "2-digit",
            second: "2-digit",
            hour12: false,
        }));
        update();
        const id = setInterval(update, 1000);
        return () => clearInterval(id);
    }, []);
    return (_jsxs("div", { className: "fixed bottom-5 left-5 z-50 flex flex-col items-start gap-3", children: [isOpen && (_jsxs("div", { className: "w-[330px] max-w-[calc(100vw-40px)] rounded-2xl bg-white shadow-2xl overflow-hidden animate-in fade-in slide-in-from-bottom-4 duration-300", children: [_jsxs("div", { className: "flex items-center gap-3 bg-gradient-to-r from-[#0088cc] to-[#229ED9] p-4 text-white", children: [_jsx("img", { src: TELEGRAM_AVATAR, alt: "Milto Engineering", className: "w-10 h-10 rounded-full object-cover shrink-0" }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsx("h4", { className: "text-sm font-semibold leading-tight truncate", children: "Milto Engineering" }), _jsx("p", { className: "text-xs text-blue-100/90 leading-tight", children: "Typically replies within a day" })] }), _jsx("button", { onClick: () => setIsOpen(false), className: "shrink-0 w-7 h-7 rounded-full flex items-center justify-center hover:bg-white/20 transition-colors", "aria-label": "Close chat", children: _jsx(X, { size: 16, weight: "bold" }) })] }), _jsxs("div", { className: "p-4 bg-gradient-to-b from-blue-50/60 to-white", children: [_jsx("p", { className: "text-center text-[10px] text-gray-400 mb-3", children: currentTime }), _jsxs("div", { className: "flex items-start gap-2 mb-3", children: [_jsx("img", { src: TELEGRAM_AVATAR, alt: "Milto Engineering", className: "w-7 h-7 rounded-full object-cover shrink-0 mt-1" }), _jsx("div", { className: "bg-white rounded-2xl rounded-tl-md px-3 py-2 shadow-sm max-w-[240px]", children: _jsx("p", { className: "text-sm text-gray-700 leading-snug", children: "Hello, Welcome to the site. Please click the button below to chat with us through Telegram." }) })] }), _jsxs("a", { href: SOCIAL.telegram, target: "_blank", rel: "noopener noreferrer", className: "flex items-center justify-center gap-2 w-full rounded-xl bg-gradient-to-r from-[#0088cc] to-[#229ED9] px-4 py-2.5 text-white text-sm font-semibold hover:opacity-90 transition-opacity", children: [_jsx(PaperPlaneTilt, { size: 16, weight: "fill" }), "Send a message"] })] })] })), _jsx("button", { onClick: () => setIsOpen((v) => !v), className: `w-14 h-14 rounded-full flex items-center justify-center text-white shadow-lg transition-all duration-300 hover:scale-110 ${isOpen
                    ? "bg-gray-700"
                    : "bg-gradient-to-br from-[#0088cc] to-[#229ED9] animate-pulse"}`, "aria-label": isOpen ? "Close Telegram chat" : "Open Telegram chat", children: isOpen ? (_jsx(X, { size: 24, weight: "bold" })) : (_jsx(TelegramLogo, { size: 26, weight: "fill" })) })] }));
}
export default function Footer() {
    const year = new Date().getFullYear();
    return (_jsxs("footer", { className: "bg-blue-950 text-white", children: [_jsx("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16 lg:py-20", children: _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-10 lg:gap-12", children: [_jsxs("div", { className: "lg:col-span-1", children: [_jsxs("div", { className: "flex items-center gap-3 mb-4", children: [_jsx("div", { className: "w-12 h-12 rounded-xl bg-white/10 flex items-center justify-center text-white font-bold text-sm", children: "ME" }), _jsxs("div", { children: [_jsx("p", { className: "text-lg font-bold leading-tight", children: BRAND.shortName }), _jsx("p", { className: "text-xs text-blue-300/70 leading-tight tracking-wider uppercase", children: "Engineering PLC" })] })] }), _jsx("p", { className: "text-sm text-blue-200/80 leading-relaxed mb-6", children: "Ethiopia's trusted Grade One Water Resources consulting and engineering firm, delivering professional services since 2021." }), _jsxs("div", { className: "flex gap-3", children: [_jsx("a", { href: SOCIAL.linkedin, target: "_blank", rel: "noopener noreferrer", className: "w-10 h-10 rounded-lg bg-white/10 flex items-center justify-center hover:bg-white/20 transition-colors", "aria-label": "LinkedIn", children: _jsx(LinkedinLogo, { size: 18, weight: "fill" }) }), _jsx("a", { href: SOCIAL.youtube, target: "_blank", rel: "noopener noreferrer", className: "w-10 h-10 rounded-lg bg-white/10 flex items-center justify-center hover:bg-white/20 transition-colors", "aria-label": "YouTube", children: _jsx(YoutubeLogo, { size: 18, weight: "fill" }) }), _jsx("a", { href: SOCIAL.telegram, target: "_blank", rel: "noopener noreferrer", className: "w-10 h-10 rounded-lg bg-white/10 flex items-center justify-center hover:bg-white/20 transition-colors", "aria-label": "Telegram", children: _jsx(TelegramLogo, { size: 18, weight: "fill" }) }), _jsx("a", { href: SOCIAL.facebook, target: "_blank", rel: "noopener noreferrer", className: "w-10 h-10 rounded-lg bg-white/10 flex items-center justify-center hover:bg-white/20 transition-colors", "aria-label": "Facebook", children: _jsx(FacebookLogo, { size: 18, weight: "fill" }) })] })] }), _jsxs("div", { children: [_jsx("h3", { className: "text-sm font-semibold uppercase tracking-wider text-blue-300 mb-5", children: "Quick Links" }), _jsx("ul", { className: "space-y-3", children: ["Home", "About", "Services", "Projects", "Team", "Contact"].map((item) => (_jsx("li", { children: _jsx("a", { href: `#${item.toLowerCase()}`, className: "text-sm text-blue-200/80 hover:text-white transition-colors", children: item }) }, item))) })] }), _jsxs("div", { children: [_jsx("h3", { className: "text-sm font-semibold uppercase tracking-wider text-blue-300 mb-5", children: "Services" }), _jsx("ul", { className: "space-y-3", children: [
                                        "Water Resources Engineering",
                                        "Groundwater & Hydrogeology",
                                        "Geophysics & Geotechnical",
                                        "Environmental Services",
                                        "GIS & Remote Sensing",
                                        "Engineering Consulting",
                                    ].map((item) => (_jsx("li", { children: _jsx("a", { href: "#services", className: "text-sm text-blue-200/80 hover:text-white transition-colors", children: item }) }, item))) })] }), _jsxs("div", { children: [_jsx("h3", { className: "text-sm font-semibold uppercase tracking-wider text-blue-300 mb-5", children: "Contact Us" }), _jsxs("ul", { className: "space-y-4", children: [_jsxs("li", { className: "flex items-start gap-3", children: [_jsx(MapPin, { size: 18, className: "text-blue-400 mt-0.5 shrink-0" }), _jsx("span", { className: "text-sm text-blue-200/80", children: BRAND.headquarters })] }), _jsx("li", { children: _jsxs("a", { href: "tel:+251901000960", className: "flex items-start gap-3 text-sm text-blue-200/80 hover:text-white transition-colors", children: [_jsx(Phone, { size: 18, className: "text-blue-400 mt-0.5 shrink-0" }), _jsx("span", { children: "+251-901-000960" })] }) }), _jsxs("li", { className: "space-y-2", children: [_jsxs("a", { href: "mailto:admin@miltoengineering.com", className: "flex items-start gap-3 text-sm text-blue-200/80 hover:text-white transition-colors", children: [_jsx(Envelope, { size: 18, className: "text-blue-400 mt-0.5 shrink-0" }), _jsx("span", { children: "admin@miltoengineering.com" })] }), _jsxs("a", { href: "mailto:miltoengineeringplc@gmail.com", className: "flex items-start gap-3 text-sm text-blue-200/80 hover:text-white transition-colors", children: [_jsx(Envelope, { size: 18, className: "text-blue-400 mt-0.5 shrink-0" }), _jsx("span", { children: "miltoengineeringplc@gmail.com" })] })] })] })] })] }) }), _jsx("div", { className: "border-t border-white/10", children: _jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 flex flex-col sm:flex-row items-center justify-between gap-4", children: [_jsxs("p", { className: "text-sm text-blue-300/70", children: ["\u00A9 ", year, " ", BRAND.name, ". All rights reserved."] }), _jsx("p", { className: "text-xs text-blue-300/50", children: "Grade One Water Resources Consulting & Engineering" })] }) }), _jsx(TelegramWidget, {})] }));
}
